        # -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '디자인샘플.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1600, 800))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("background-color : black;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(500, 50, 600, 250))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/youtube-logo.jpg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setGeometry(QtCore.QRect(650, 370, 300, 30))
        self.lineEdit.setStyleSheet("background-color : white;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(650, 320, 100, 35))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color : white;")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.lineEdit_2.setGeometry(QtCore.QRect(650, 420, 300, 30))
        self.lineEdit_2.setStyleSheet("background-color : white;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(595, 370, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color : white;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page)
        self.label_10.setGeometry(QtCore.QRect(590, 420, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color : white;")
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(650, 510, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color : red;\n"
"color : white;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(890, 565, 60, 28))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        font.setKerning(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("color : white;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(650, 460, 300, 15))
        self.label_11.setStyleSheet("color : red;")
        self.label_11.setObjectName("label_11")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(735, 80, 170, 45))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color : white;")
        self.label_12.setObjectName("label_12")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_9.setGeometry(QtCore.QRect(650, 210, 300, 30))
        self.lineEdit_9.setStyleSheet("background-color : white;\n"
"")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_10.setGeometry(QtCore.QRect(650, 310, 300, 30))
        self.lineEdit_10.setStyleSheet("background-color : white;\n"
"")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(650, 370, 300, 30))
        self.lineEdit_11.setStyleSheet("background-color : white;\n"
"")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_12.setGeometry(QtCore.QRect(650, 470, 300, 30))
        self.lineEdit_12.setStyleSheet("background-color : white;\n"
"")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(650, 250, 210, 15))
        self.label_13.setStyleSheet("color : red;")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setGeometry(QtCore.QRect(650, 180, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color : white;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setGeometry(QtCore.QRect(650, 280, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color : white;")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_2)
        self.label_16.setGeometry(QtCore.QRect(650, 345, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color : white;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_2)
        self.label_17.setGeometry(QtCore.QRect(650, 445, 35, 20))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color : white;")
        self.label_17.setObjectName("label_17")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(970, 210, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background-color : red;\n"
"color : white;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(650, 410, 210, 15))
        self.label_18.setStyleSheet("color : red;")
        self.label_18.setObjectName("label_18")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_4.setGeometry(QtCore.QRect(650, 570, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("background-color : red;\n"
"color : white;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.page_2)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.label_19 = QtWidgets.QLabel(self.page_9)
        self.label_19.setGeometry(QtCore.QRect(30, 30, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color : white;")
        self.label_19.setObjectName("label_19")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_5.setGeometry(QtCore.QRect(1430, 40, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("color : white;\n"
"background-color : red;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_6.setGeometry(QtCore.QRect(1250, 40, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("color : white;\n"
"background-color : red;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.scrollArea = QtWidgets.QScrollArea(self.page_9)
        self.scrollArea.setGeometry(QtCore.QRect(550, 140, 500, 561))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(100, 100, 277, 285))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setMinimumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color : white;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setMinimumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color : white;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_8)
        self.pushButton_17 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_17.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_17.setStyleSheet("background-color : white;")
        self.pushButton_17.setObjectName("pushButton_17")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_18.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_18.setStyleSheet("background-color : white;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_19.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_19.setStyleSheet("background-color : white;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pushButton_19)
        self.pushButton_20 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_20.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_20.setStyleSheet("background-color : white;")
        self.pushButton_20.setObjectName("pushButton_20")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_21.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_21.setStyleSheet("background-color : white;")
        self.pushButton_21.setObjectName("pushButton_21")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pushButton_21)
        self.pushButton_22 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_22.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_22.setStyleSheet("background-color : white;")
        self.pushButton_22.setObjectName("pushButton_22")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pushButton_22)
        self.pushButton_23 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_23.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_23.setStyleSheet("background-color : white;")
        self.pushButton_23.setObjectName("pushButton_23")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_24.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_24.setStyleSheet("background-color : white;")
        self.pushButton_24.setObjectName("pushButton_24")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pushButton_24)
        self.pushButton_25 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_25.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_25.setStyleSheet("background-color : white;")
        self.pushButton_25.setObjectName("pushButton_25")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_26.setMinimumSize(QtCore.QSize(20, 50))
        self.pushButton_26.setStyleSheet("background-color : white;")
        self.pushButton_26.setObjectName("pushButton_26")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pushButton_26)
        self.pushButton_9 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_9.setMinimumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color : white;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_10.setMinimumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("background-color : white;")
        self.pushButton_10.setObjectName("pushButton_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_11.setMinimumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("background-color : white;")
        self.pushButton_11.setObjectName("pushButton_11")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_12.setMinimumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("background-color : white;")
        self.pushButton_12.setObjectName("pushButton_12")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_13.setMinimumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color : white;")
        self.pushButton_13.setObjectName("pushButton_13")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_14.setMinimumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("background-color : white;")
        self.pushButton_14.setObjectName("pushButton_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_15.setMinimumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("background-color : white;")
        self.pushButton_15.setObjectName("pushButton_15")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.pushButton_15)
        self.pushButton_16 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_16.setMinimumSize(QtCore.QSize(380, 50))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("background-color : white;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.pushButton_16)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.pushButton_27 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_27.setGeometry(QtCore.QRect(1250, 40, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_27.setStyleSheet("color : white;\n"
"background-color : red;")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_28.setGeometry(QtCore.QRect(1430, 40, 150, 35))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_28.setStyleSheet("color : white;\n"
"background-color : red;")
        self.pushButton_28.setObjectName("pushButton_28")
        self.label_20 = QtWidgets.QLabel(self.page_10)
        self.label_20.setGeometry(QtCore.QRect(110, 60, 1000, 600))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: white;")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page_10)
        self.label_21.setGeometry(QtCore.QRect(470, 720, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color : red;\n"
"color : white;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.page_10)
        self.label_22.setGeometry(QtCore.QRect(610, 720, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color : red;\n"
"color : white;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_10)
        self.label_23.setGeometry(QtCore.QRect(330, 720, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color : red;\n"
"color : white;")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page_10)
        self.label_24.setGeometry(QtCore.QRect(110, 670, 441, 21))
        self.label_24.setStyleSheet("color :white;")
        self.label_24.setObjectName("label_24")
        self.listWidget = QtWidgets.QListWidget(self.page_10)
        self.listWidget.setGeometry(QtCore.QRect(1280, 120, 191, 551))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_29 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_29.setGeometry(QtCore.QRect(1480, 120, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_29.setStyleSheet("color : white;\n"
"background-color : red;")
        self.pushButton_29.setObjectName("pushButton_29")
        self.label_25 = QtWidgets.QLabel(self.page_10)
        self.label_25.setGeometry(QtCore.QRect(1290, 140, 161, 16))
        self.label_25.setStyleSheet("color : white;")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.page_10)
        self.label_26.setGeometry(QtCore.QRect(1290, 160, 161, 16))
        self.label_26.setStyleSheet("color : white;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.page_10)
        self.label_27.setGeometry(QtCore.QRect(1290, 180, 151, 16))
        self.label_27.setStyleSheet("color : white;")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.page_10)
        self.label_28.setGeometry(QtCore.QRect(1290, 200, 161, 16))
        self.label_28.setStyleSheet("color : white;")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.page_10)
        self.label_29.setGeometry(QtCore.QRect(1290, 220, 151, 16))
        self.label_29.setStyleSheet("color : white;")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.page_10)
        self.label_30.setGeometry(QtCore.QRect(1290, 240, 161, 16))
        self.label_30.setStyleSheet("color : white;")
        self.label_30.setObjectName("label_30")
        self.stackedWidget.addWidget(self.page_10)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "로그인"))
        self.label_9.setText(_translate("MainWindow", "ID"))
        self.label_10.setText(_translate("MainWindow", "PW"))
        self.pushButton.setText(_translate("MainWindow", "로그인"))
        self.pushButton_2.setText(_translate("MainWindow", "회원가입"))
        self.label_11.setText(_translate("MainWindow", "아이디 또는 비밀번호를 확인해주세요!"))
        self.label_12.setText(_translate("MainWindow", "회원가입"))
        self.label_13.setText(_translate("MainWindow", "이미 사용중인 아이디입니다!"))
        self.label_14.setText(_translate("MainWindow", "아이디"))
        self.label_15.setText(_translate("MainWindow", "비밀번호"))
        self.label_16.setText(_translate("MainWindow", "비밀번호 확인"))
        self.label_17.setText(_translate("MainWindow", "이름"))
        self.pushButton_3.setText(_translate("MainWindow", "중복확인"))
        self.label_18.setText(_translate("MainWindow", "비밀번호가 일치하지 않습니다!"))
        self.pushButton_4.setText(_translate("MainWindow", "회원가입"))
        self.label_19.setText(_translate("MainWindow", "사용자 : Test"))
        self.pushButton_5.setText(_translate("MainWindow", "뒤로가기"))
        self.pushButton_6.setText(_translate("MainWindow", "+ 재생목록 만들기"))
        self.pushButton_7.setText(_translate("MainWindow", "재생목록1"))
        self.pushButton_8.setText(_translate("MainWindow", "재생목록1"))
        self.pushButton_17.setText(_translate("MainWindow", "삭제"))
        self.pushButton_18.setText(_translate("MainWindow", "삭제"))
        self.pushButton_19.setText(_translate("MainWindow", "삭제"))
        self.pushButton_20.setText(_translate("MainWindow", "삭제"))
        self.pushButton_21.setText(_translate("MainWindow", "삭제"))
        self.pushButton_22.setText(_translate("MainWindow", "삭제"))
        self.pushButton_23.setText(_translate("MainWindow", "삭제"))
        self.pushButton_24.setText(_translate("MainWindow", "삭제"))
        self.pushButton_25.setText(_translate("MainWindow", "삭제"))
        self.pushButton_26.setText(_translate("MainWindow", "삭제"))
        self.pushButton_9.setText(_translate("MainWindow", "재생목록1"))
        self.pushButton_10.setText(_translate("MainWindow", "재생목록1"))
        self.pushButton_11.setText(_translate("MainWindow", "재생목록1"))
        self.pushButton_12.setText(_translate("MainWindow", "재생목록1"))
        self.pushButton_13.setText(_translate("MainWindow", "재생목록1"))
        self.pushButton_14.setText(_translate("MainWindow", "재생목록1"))
        self.pushButton_15.setText(_translate("MainWindow", "재생목록1"))
        self.pushButton_16.setText(_translate("MainWindow", "재생목록1"))
        self.pushButton_27.setText(_translate("MainWindow", "+ 영상추가"))
        self.pushButton_28.setText(_translate("MainWindow", "뒤로가기"))
        self.label_20.setText(_translate("MainWindow", "동영상 출력 화면"))
        self.label_21.setText(_translate("MainWindow", "▶"))
        self.label_22.setText(_translate("MainWindow", "❚❚"))
        self.label_23.setText(_translate("MainWindow", "■"))
        self.label_24.setText(_translate("MainWindow", "영상제목~~~~~"))
        self.pushButton_29.setText(_translate("MainWindow", "삭제"))
        self.label_25.setText(_translate("MainWindow", "영상제목"))
        self.label_26.setText(_translate("MainWindow", "영상제목"))
        self.label_27.setText(_translate("MainWindow", "영상제목"))
        self.label_28.setText(_translate("MainWindow", "영상제목"))
        self.label_29.setText(_translate("MainWindow", "영상제목"))
        self.label_30.setText(_translate("MainWindow", "영상제목"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

